### Testing
GET https://localhost:8000/ HTTP/1.1
User-Agent: Min Kg Kyaw
Content-Type: application/json

### Applicants

# get applicants
GET https://localhost:8000/api/applicants HTTP/1.1
User-Agent: Min Kg Kyaw
Content-Type: application/json