### get CSRF token
GET https://localhost:8000/csrf_token HTTP/1.1
User-Agent: Min Kg Kyaw
Content-Type: application/json

###  post applicants
POST https://localhost:8000/api/applicants HTTP/1.1
User-Agent: Min Kaung Kyaw
Content-Type: application/json
csrf-token: hz5mZSXc-dM3MmHehn2b-0MUXl5hhDnlhXT0

{
  "firstName": "Min Kg",
  "lastName": "Kyaw",
  "email": "mwebeducationchannel@gmail.com",
  "password": "mkk123",
  "confirmPassword": "mkk123",
  "gender": "Male",
  "role": "Developer"
}

### get applicants
GET https://localhost:8000/api/applicants HTTP/1.1
User-Agent: Min Kg Kyaw
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJQUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDE0Y2I4YWNiZmE0NmZkOWVlYWE2MSIsInJvbGUiOiJEZXZlbG9wZXIiLCJwYXNzd29yZCI6IiQyYiQxMCRMWldDbzRxbE1nZWZrTkpvZFdDc2JPb1lsYllkYlhOWkJ1SGJUMWV0UVUwOVFzanBlUGtocSIsImlhdCI6MTY0ODQ2MDE4MSwiZXhwIjoxNjc5OTk2MTgxfQ.412xKq0XYe3qFYnpB8L3Thu0PBjJZYjwRrDR4NgI96qLgDTKURTerppqf9unr5uIPKQItLU0Q002XeXYjcny4y7N38yDwem_Jm8mO1v_Gn1uTB5AGVe8S0x88FJnOfSZG__7Zn8S8Tf_N91TVA8Odjk-Gd7piTMo7ecbLr1xcp_N-kIEAMv4iTUYEV-x6h2NXYU2WqDt4Uc7i6MJaTlZSyBALw1HOScynIByPtUWLvQpgBcpsETtNHHVYXn9ty4RcpA8n34jVyechmOYO7vfvAx7LLSiQcb_2TSgEq3EkLYm7EbAu9zs-_usAXFWbfAyjJ9Dow492qWrC8R5EM2r_zGFquM9Az9WhQ2xngIqkXoD_ByvsNBzyAgMxcjQU7DRj54v5FGUFLo_-dkRulLSIypm5ekvTLC5-m-6eoHwQzmny3kXpE7bPGv9nqrtD-QYhjSt_bNQHG-QIMmlXKg0LONjr8KfYU1ibvQ_qSZ2FDa4KfJOn8ETr6xGppkE9fhsD-GwaWSsTZglg_UaTqNO9oR3SKxHXspMOehN8gJcmlSUQp30j9Cvs23zU55NKgehx9r7lWQCyE0eZQlvvAUpy1CGdJMWFJ6mAydgvUQaETF-UjMNcxLCve93IX4yLY1_UrkLi8hB3lzV-I4Ld87mY63ojY3ktap_YT561_4hn_I

### get applicant by id 
GET https://localhost:8000/api/applicants/623fee9c61fc55285ad0f13a HTTP/1.1
User-Agent: Min Kg Kyaw 
Content-Type: application/json

### delete applicant by id 
DELETE https://localhost:8000/api/applicants/623fe1a591c4b9b446233faa HTTP/1.1
User-Agent: Min Kg Kyaw
csrf-token: hz5mZSXc-dM3MmHehn2b-0MUXl5hhDnlhXT0

### verify applicant
GET https://localhost:8000/api/applicants/verify?verificationToken=ce5fa61f6bb23cc4bb2ea6c6c9a78b0fbe048a4aaf47e5eabea777fa1e999618

### login (auth) true
POST https://localhost:8000/api/auth/login
User-Agent: Min Kg Kyaw
Content-Type: application/json
csrf-token: YjEBBpC8-oVV1ufmrKNVGXbUgmmrVVDF9ngU

{
  "email": "mwebeducationchannel@gmail.com",
  "password": "mkk123"
}

### login (auth) false
POST https://localhost:8000/api/auth/login
User-Agent: Min Kg Kyaw
Content-Type: application/json
csrf-token: YjEBBpC8-oVV1ufmrKNVGXbUgmmrVVDF9ngU

{
  "email": "mkk@gmail.com",
  "password": "mkk123"
}

### get all users
GET https://localhost:8000/api/users

### get user by id
GET https://localhost:8000/api/users/62414cb8acbfa46fd9eeaa61 
Authorization: Bearer eyJhbGciOiJQUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDE0Y2I4YWNiZmE0NmZkOWVlYWE2MSIsInJvbGUiOiJEZXZlbG9wZXIiLCJwYXNzd29yZCI6IiQyYiQxMCRMWldDbzRxbE1nZWZrTkpvZFdDc2JPb1lsYllkYlhOWkJ1SGJUMWV0UVUwOVFzanBlUGtocSIsImlhdCI6MTY0ODQ1NTA1NiwiZXhwIjoxNjc5OTkxMDU2fQ.DLAXLvcB0ltBTyR0pCjoSVdhgFSnnXJeJ2rZ5QnTaqQ-bR5yNJibpJXVqACIfRlaXKTLhwsyN0puutMBYVpdqteyaq8qf-d8-msrLgWdW5EKCf6QCCnRA2YrS_Mu3ngLkWXHo8AGAj5xc_hDzNuNMBZtH6iL-qZOPtaISe3qVdtStujj1KTDXpTGpc4ymhtquEBy0fOWD5W0Ittxm2v3uPCfxWdRDHERpvwLAQai1ZNEQnscJuPVfI9bkw-tvZ98w0bSpX7Q_DlEFFV5waSoIwZXh-npvCA5yyDrlxaC4sHvDPBWnxr_vzR-q5fASu7OPnsbmWQSeumsubO2nKL_Gv-_0Fy43yRLEhHwyUNNyVTl0ejEEjc2jSkLzxo6cC8PiBmGDfwwT6w3QIl6prKeaRCeBpTh4azy0TTn_9PDCotOC0qKLEyLc2EyT7FWuSJb-yrKqGdx6m9T6FC4KLzfu-eawiwF5lTQ5b8CZBETh2ZmCUfH9oEoYWKu_XWK52Ewse1QY6BjPRtRprg8glemTafCnQkmOmz4eebT00yp8Qozv7W_0dhpDEz9W3hksT0SFW50KBT-5wKmiMYZLQcSrruamlSoLUrNDEJDzG-psHFVUMCXKuV3Hc90FFobjFueWY0v5lLMk_WmxSkIIOt8GJGP_4a3Wv-joLzKonWPLEA