### get CSRF token
GET https://localhost:8000/csrf_token HTTP/1.1
User-Agent: Min Kg Kyaw
Content-Type: application/json

###  post applicants
POST https://localhost:8000/api/applicants HTTP/1.1
User-Agent: Min Kaung Kyaw
Content-Type: application/json
csrf-token: hz5mZSXc-dM3MmHehn2b-0MUXl5hhDnlhXT0

{
  "firstName": "Min Kg",
  "lastName": "Kyaw",
  "email": "mwebeducationchannel@gmail.com",
  "password": "mkk123",
  "confirmPassword": "mkk123",
  "gender": "Male",
  "role": "Developer"
}

### get applicants
GET https://localhost:8000/api/applicants HTTP/1.1
User-Agent: Min Kg Kyaw
Content-Type: application/json

### get applicant by id 
GET https://localhost:8000/api/applicants/623fee9c61fc55285ad0f13a HTTP/1.1
User-Agent: Min Kg Kyaw 
Content-Type: application/json

### delete applicant by id 
DELETE https://localhost:8000/api/applicants/623fe1a591c4b9b446233faa HTTP/1.1
User-Agent: Min Kg Kyaw
csrf-token: hz5mZSXc-dM3MmHehn2b-0MUXl5hhDnlhXT0

### verify applicant
GET https://localhost:8000/api/applicants/verify?verificationToken=a97a1d22e545256c62ca8a925a3a9875056589f6da2a8575c0084c7f08485f9a

### login (auth)
POST https://localhost:8000/api/auth/login
User-Agent: Min Kg Kyaw
Content-Type: application/json
csrf-token: YjEBBpC8-oVV1ufmrKNVGXbUgmmrVVDF9ngU

{
  "email": "mwebeducationchannel@gmail.com",
  "password": "mkk123"
}

### login (auth)
POST https://localhost:8000/api/auth/login
User-Agent: Min Kg Kyaw
Content-Type: application/json
csrf-token: YjEBBpC8-oVV1ufmrKNVGXbUgmmrVVDF9ngU

{
  "email": "mwebeducationchannel@gmail.com",
  "password": "mkk123"
}

### get all users
GET https://localhost:8000/api/users

### get user by id
GET https://localhost:8000/api/users/623ff46114168d06bc227b6b